services:
  backend:
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    ports:
      - "4000:4000"
  frontend:
    build:
      context: ./frontend
      dockerfile: frontend.dockerfile
    ports:
      - "5173:5173"
