name: CI

on:
  push:
    branches:
      - "feature/CICD"


permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "18"
      - run: npm --prefix ./frontend ci
      - run: npm --prefix ./frontend run test
      - run: percentage=$(grep -oP '^\s*\d+(,\d+)?%' ./coverage/index.html | head -n 1) percentage_float=$(echo "$percentage" | sed 's/%//g' | sed 's/,/./g') if (( $(echo "$percentage_float > 10" | bc -l) )); then echo "Percentage is above 10%"  else  echo "Percentage is below 10%"exit 1 fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}