name: CI

on:
  push:
    branches:
      - "feature/CICD"


permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "18"
      - run: npm --prefix ./frontend ci
      - run: npm --prefix ./frontend run test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
