name: CI

on:
  push:
    branches:
      - "feature/CICD"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "18"
      - run: npm --prefix ./frontend ci
      - run: npm --prefix ./frontend run test
      - run: npx -p check-code-coverage set-gh-status eslint