name: Release

on:
  push:
    branches:
      - main
      - 'release/v*'

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  frontend-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - run: cd ./frontend
      - run: npm ci
      - run: npm build
      - run: npm audit signatures
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm run semantic-release
  backend-release:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-go@v4
          with:
            go-version: 1.19
        - run: cd ./backend
        - uses: go-semantic-release/action@v1
          with:
            hooks: goreleaser
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}